application: fortifi-elements
version: 1
runtime: php55
api_version: 1

handlers:
- url: /bower_components
  static_dir: bower_components

- url: /data
  static_dir: data

- url: /guides
  static_dir: guides

- url: /styles
  static_dir: styles

- url: /elements/fort-.*
  script: /index.html

- url: /elements
  static_dir: elements

- url: /images
  static_dir: images

- url: /catalog.json
  static_files: catalog.json
  upload: catalog.json

- url: /.*
  script: /index.html
